name: Check

on:
  push:
    branches: ['*']

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.6'
      - name: Install go dependencies
        run: |
          go install golang.org/x/lint/golint@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go get github.com/stretchr/testify/assert
          go get github.com/vektra/mockery/v2/.../
      - name: Run checks
        run: |
          make all
